use customer_behaviour;
select * from customer;

-- PROBLEM: Total Revenue generated by male v/s female customers:
select gender,sum(purchase_amount) as Revenue
from customer
group by gender;

-- INSIGHT: Now the above Revenue Generated will help company target customers and launch campaigns accordingly.


-- PROBLEM: To find Customers who used discount but spend more than average purchase amount:
select customer_id, purchase_amount from customer
where discount_applied  = 'YES'
and purchase_amount >= (select avg(purchase_amount) from customer) ;


-- PROBLEM: Top 5 products with highest average review rating?
select item_purchased, round(avg(review_rating), 2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc limit 5;

-- INSIGHT: Now this highly rated products can be more highlighted in campaigns as their best selling products.
-- Also they can be sold at premium prices so as to make more profits.

-- PROBLEM: To compare the average purchase amount between standard and express shipping
select shipping_type , avg(purchase_amount) as 'Avg purchase amount' from customer
where shipping_type in ("Express", "Standard")
group by shipping_type;

-- PROBLEM: Do subscribers spend more? Compare avg spend and total revenue between subscribers and non- subscribers
select subscription_status, 
count(customer_id) as total_customers,
round(sum(purchase_amount), 2) as total_revenue,
round(avg(purchase_amount), 2) as avg_spend
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- PROBLEM: To find which are the 5 products which have the highest percentage of purchases with discounts applied
SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
 -- INSIGHT : for ex if a hat was sold 10 times -> then 50% of the time a discount was applied
 -- This helps us better understand which products rely heavily on discounts to sell.
 
 -- PROBLEM: To segment customers on new, returning, loyal, based on their total number of previous purchases
 -- and show the count of each segment.
 -- ( we will'be segmenting customers as 1: new, (2-10): returning, (more than 10): loyal
 with customer_type as (
 select customer_id, previous_purchases,
 case
	when previous_purchases = 1 then "New"
    when previous_purchases between 2 and 10 then "Returning"
    else "Loyal"
    end as customer_segment
from customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
GROUP BY customer_segment;

-- INSIGHT: This tells us there are lot of loyal customers- almost 80%.


-- PROBLEM: Top 3 most purchased products from each category.
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders
    FROM customer
    GROUP BY category, item_purchased
),
ranked_items AS (
    SELECT
        category,
        item_purchased,
        total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY total_orders DESC) AS item_rank
    FROM item_counts
)
SELECT 
    item_rank, 
    category, 
    item_purchased, 
    total_orders
FROM ranked_items
WHERE item_rank <= 3;


-- PROBLEM: Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status, 
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5 
group by subscription_status;

-- PROBLEM: What is the Revenue contribution of each age group
select age_group,
sum(purchase_amount) as Total_Revenue
from customer
group by age_group
order by Total_Revenue Desc;

-- INSIGHT: This tells us which demographics is most valuable to the business. 
-- Young Adult drives the most revenue

